import { CollectionLogCategory } from './types';

export const COLLECTION_LOG_CATEGORIES: CollectionLogCategory[] = [
  // ── Boss Drops ──────────────────────────────────────────────
  {
    id: 'boss_drops',
    name: 'Boss Drops',
    icon: '💀',
    items: [
      'abyssal_whip',
      'armadyl_godsword',
      'godsword_shard_1',
      'godsword_shard_2',
      'godsword_shard_3',
      'godsword_blade',
      'armadyl_hilt',
      'obsidian_maul',
      'ancient_staff',
      'black_mask',
      'dragon_lord_seal',
      'dragon_lord_trophy',
      'imperial_seal',
      'imperial_crown',
      'dragon_fang',
      'dragon_scale',
      'dark_energy_core',
      'abyssal_head',
    ],
  },

  // ── Raids Loot ──────────────────────────────────────────────
  {
    id: 'raids_loot',
    name: 'Raids Loot',
    icon: '🏛️',
    items: [
      'raid_relic',
      'ancient_relic',
      'void_blade',
      'void_essence',
      'void_shard',
      'void_reaper_trophy',
      'void_horror_trophy',
      'void_relic_casket',
    ],
  },

  // ── Slayer Creatures ────────────────────────────────────────
  {
    id: 'slayer_creatures',
    name: 'Slayer Creatures',
    icon: '🗡️',
    items: [
      'crawler_meat',
      'bug_shell',
      'rockslug_slime',
      'cockatrice_egg',
      'basilisk_jaw',
      'kurask_horn',
      'gargoyle_granite',
      'demon_horn',
      'ogre_tooth',
      'giant_toe',
      'elf_dust',
      'vampire_dust',
      'hellhound_ash',
      'spider_venom',
      'smoke_essence',
    ],
  },

  // ── Mining & Smithing ───────────────────────────────────────
  {
    id: 'mining_smithing',
    name: 'Mining & Smithing',
    icon: '⛏️',
    items: [
      'copper_ore',
      'tin_ore',
      'iron_ore',
      'coal',
      'steel_ore',
      'mithril_ore',
      'adamant_ore',
      'runite_ore',
      'silver_ore',
      'platinum_ore',
      'gold_ore',
      'obsidian',
      'dragonite_ore',
      'necrite_ore',
      'clay',
      'limestone',
      'granite',
      'sandstone',
      'basalt',
      'marble',
      'bronze_bar',
      'iron_bar',
      'steel_bar',
      'mithril_bar',
      'adamant_bar',
      'runite_bar',
      'silver_bar',
      'platinum_bar',
      'gold_bar',
      'dragonite_bar',
      'necrite_bar',
      'orichalcum_bar',
    ],
  },

  // ── Woodcutting & Crafting ──────────────────────────────────
  {
    id: 'woodcutting_crafting',
    name: 'Woodcutting & Crafting',
    icon: '🪓',
    items: [
      'logs',
      'dry_logs',
      'achey_logs',
      'pine_logs',
      'oak_logs',
      'eucalyptus_logs',
      'teak_logs',
      'willow_logs',
      'mahogany_logs',
      'blisterwood_logs',
      'yew_logs',
      'magic_logs',
      'elder_logs',
      'bloodwood_logs',
      'reinforced_leather',
      'enchanted_string',
      'silk',
      'flax',
      'wool',
      'feathers',
      'bird_nest',
    ],
  },

  // ── Fishing & Cooking ──────────────────────────────────────
  {
    id: 'fishing_cooking',
    name: 'Fishing & Cooking',
    icon: '🐟',
    items: [
      'raw_shrimp',
      'raw_sardine',
      'raw_herring',
      'raw_anchovies',
      'raw_mackerel',
      'raw_pike',
      'raw_tuna',
      'raw_cod',
      'raw_bass',
      'raw_swordfish',
      'raw_monkfish',
      'raw_karambwan',
      'raw_mantaray',
      'cooked_shrimp',
      'cooked_sardine',
      'cooked_herring',
      'cooked_anchovies',
      'cooked_mackerel',
      'cooked_pike',
      'cooked_tuna',
      'cooked_cod',
      'cooked_bass',
      'cooked_swordfish',
      'cooked_monkfish',
      'cooked_karambwan',
      'cooked_mantaray',
      'raw_chicken',
      'cooked_chicken',
      'raw_beef',
      'cooked_beef',
      'raw_bear_meat',
      'cooked_bear_meat',
      'raw_rabbit',
      'cooked_rabbit',
      'raw_boar_meat',
      'cooked_boar_meat',
      'raw_stag_meat',
      'cooked_stag_meat',
    ],
  },

  // ── Herblore & Potions ─────────────────────────────────────
  {
    id: 'herblore_potions',
    name: 'Herblore & Potions',
    icon: '🧪',
    items: [
      'luck_potion',
      'overload_potion',
      'agility_elixir',
      'thief_brew',
      'prayer_potion',
      'dragon_slayer_potion',
      'antipoison',
      'vial_of_water',
      'herb_mix',
    ],
  },

  // ── Runecrafting ────────────────────────────────────────────
  {
    id: 'runecrafting',
    name: 'Runecrafting',
    icon: '🔮',
    items: [
      'rune_essence',
      'divine_essence',
      'air_rune',
      'mind_rune',
      'water_rune',
      'earth_rune',
      'fire_rune',
      'cosmic_rune',
      'chaos_rune',
      'astral_rune',
      'nature_rune',
      'death_rune',
      'law_rune',
      'blood_rune',
      'soul_rune',
      'wrath_rune',
    ],
  },

  // ── Thieving ────────────────────────────────────────────────
  {
    id: 'thieving',
    name: 'Thieving',
    icon: '🦝',
    items: [
      'lockpick',
      'coin_purse',
      'mark_of_grace',
    ],
  },

  // ── Combat Equipment ────────────────────────────────────────
  {
    id: 'combat_equipment',
    name: 'Combat Equipment',
    icon: '⚔️',
    items: [
      'bronze_sword',
      'iron_sword',
      'steel_sword',
      'mithril_sword',
      'imperial_sword',
      'platinum_sword',
      'dragon_slayer_blade',
      'copper_helmet',
      'leather_body',
      'iron_chainbody',
      'bronze_chainbody',
      'dragon_med_helm',
      'dragon_sq_shield',
      'dragon_platebody',
      'dragon_platelegs',
      'dragon_chainbody',
      'dragonite_body',
      'primordial_boots',
      'pegasian_boots',
      'eternal_boots',
      'rune_boots',
      'graceful_boots',
      'ring_of_wealth',
      'warrior_ring',
      'berserker_ring',
      'amulet_of_fury',
      'torture_amulet',
      'anguish_necklace',
      'tormented_bracelet',
      'occult_necklace',
    ],
  },

  // ── Gems & Jewelry ─────────────────────────────────────────
  {
    id: 'gems_jewelry',
    name: 'Gems & Jewelry',
    icon: '💎',
    items: [
      'uncut_sapphire',
      'uncut_emerald',
      'uncut_ruby',
      'uncut_diamond',
      'uncut_zenyte',
      'ruby_gem',
      'sapphire_gem',
      'emerald_gem',
      'diamond_gem',
      'void_gem',
      'zenyte_shard',
      'pearl',
    ],
  },

  // ── Dragon Collection ───────────────────────────────────────
  {
    id: 'dragon_collection',
    name: 'Dragon Collection',
    icon: '🐉',
    items: [
      'dragon_bones',
      'dragon_fang',
      'dragon_scale_shard',
      'dragon_scale',
      'iron_dragon_scale',
      'steel_dragon_scale',
      'mithril_dragon_scale',
      'adamant_dragon_scale',
      'rune_dragon_scale',
      'dragon_med_helm',
      'dragon_sq_shield',
      'dragon_platebody',
      'dragon_platelegs',
      'dragon_chainbody',
      'dragon_slayer_blade',
      'dragon_slayer_potion',
      'dragon_lord_seal',
      'dragon_lord_trophy',
    ],
  },

  // ── Void Collection ─────────────────────────────────────────
  {
    id: 'void_collection',
    name: 'Void Collection',
    icon: '🌑',
    items: [
      'void_blade',
      'void_shard',
      'void_essence',
      'void_gem',
      'void_reaper_trophy',
      'void_horror_trophy',
      'void_relic_casket',
      'dark_energy_core',
    ],
  },

  // ── Skillcapes ──────────────────────────────────────────────
  {
    id: 'skillcapes',
    name: 'Skillcapes',
    icon: '🎓',
    items: [
      'infernal_cape',
      'cape_mining',
      'cape_woodcutting',
      'cape_fishing',
      'cape_cooking',
      'cape_smithing',
      'cape_crafting',
      'cape_thieving',
      'cape_herblore',
      'cape_slayer',
    ],
  },

  // ── Treasure Trails ─────────────────────────────────────────
  {
    id: 'treasure_trails',
    name: 'Treasure Trails',
    icon: '🗺️',
    items: [
      'bronze_loot_bag',
      'iron_loot_chest',
      'gold_treasure_coffer',
      'clue_scroll_master',
      'clue_reward_box',
    ],
  },

  // ── Relics & Edicts ─────────────────────────────────────────
  {
    id: 'relics_edicts',
    name: 'Relics & Edicts',
    icon: '📜',
    items: [
      'edict_efficiency',
      'edict_prosperity',
      'edict_wisdom',
      'edict_martial_law',
      'relic_storm_eye',
      'relic_empire_heart',
      'relic_void_blade',
      'relic_eternal_wisdom',
    ],
  },

  // ── Tools ───────────────────────────────────────────────────
  {
    id: 'tools',
    name: 'Tools',
    icon: '🔨',
    items: [
      'bronze_pickaxe',
      'iron_pickaxe',
      'bronze_axe',
    ],
  },

  // ── Seeds & Farming ─────────────────────────────────────────
  {
    id: 'seeds_farming',
    name: 'Seeds & Farming',
    icon: '🌱',
    items: [
      'potato_seeds',
      'onion_seeds',
      'herb_seeds',
      'willow_seeds',
      'toadflax_seeds',
      'yew_seeds',
      'magic_seeds',
      'spirit_seed',
    ],
  },

  // ── Bones & Prayer ─────────────────────────────────────────
  {
    id: 'bones_prayer',
    name: 'Bones & Prayer',
    icon: '🦴',
    items: [
      'bones',
      'big_bones',
      'dragon_bones',
      'wolf_bone',
      'giant_bone',
      'demon_bone',
      'ancient_bone',
      'bone_meal',
    ],
  },

  // ── Monster Drops ───────────────────────────────────────────
  {
    id: 'monster_drops',
    name: 'Monster Drops',
    icon: '👹',
    items: [
      'goblin_ear',
      'wolf_pelt',
      'beast_claw',
      'monster_hide',
      'zombie_brain',
      'vial_of_blood',
      'magic_scrap',
    ],
  },
];
